import type {NextPage} from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {useState} from "react";
import TestComponent from "../components/TestComponent";

const Home: NextPage = () => {

    const [user, setUser] = useState<{username: string}>({username: "tomheaton"});

    return (
        <div className={styles.container}>
            <Head>
                <title>Project Tracker</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <TestComponent/>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to the Project Tracker
                </h1>

                <div className={styles.grid}>
                    <Link href="/users" >
                        <div className={styles.card}>
                            <h2>Users &rarr;</h2>
                            <p>View all users.</p>
                        </div>
                    </Link>

                    <Link href="/projects">
                        <div className={styles.card}>
                            <h2>Projects &rarr;</h2>
                            <p>View all projects.</p>
                        </div>
                    </Link>

                    {user && user.username ? (
                        <>
                            <Link href="/profile">
                                <div className={styles.card}>
                                    <h2>My Profile &rarr;</h2>
                                    <p>View profile and manage account settings.</p>
                                </div>
                            </Link>
                            <Link href="/api/logout">
                                <div className={styles.card}>
                                    <h2>Logout &rarr;</h2>
                                    <p>Logout of the Project Tracker.</p>
                                </div>
                            </Link>
                        </>
                    ) : (
                        <a href="" className={styles.card}>
                            <h2>Login &rarr;</h2>
                            <p>Login to the Project Tracker.</p>
                        </a>
                    )}
                </div>
            </main>
        </div>
    );
}

export default Home;
